env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - 2
    - 4
  linebreak-style:
    - linux
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
